#[repr(u32)]
pub enum CbReason {
    ValueChange = vpi_sys::cbValueChange,
    Stmt = vpi_sys::cbStmt,
    Force = vpi_sys::cbForce,
    Release = vpi_sys::cbRelease,
    AtStartOfSimTime = vpi_sys::cbAtStartOfSimTime,
    ReadWriteSynch = vpi_sys::cbReadWriteSynch,
    ReadOnlySynch = vpi_sys::cbReadOnlySynch,
    NextSimTime = vpi_sys::cbNextSimTime,
    AfterDelay = vpi_sys::cbAfterDelay,
    EndOfCompile = vpi_sys::cbEndOfCompile,
    StartOfSimulation = vpi_sys::cbStartOfSimulation,
    EndOfSimulation = vpi_sys::cbEndOfSimulation,
    Error = vpi_sys::cbError,
    TchkViolation = vpi_sys::cbTchkViolation,
    StartOfSave = vpi_sys::cbStartOfSave,
    EndOfSave = vpi_sys::cbEndOfSave,
    StartOfRestart = vpi_sys::cbStartOfRestart,
    EndOfRestart = vpi_sys::cbEndOfRestart,
    StartOfReset = vpi_sys::cbStartOfReset,
    EndOfReset = vpi_sys::cbEndOfReset,
    EnterInteractive = vpi_sys::cbEnterInteractive,
    ExitInteractive = vpi_sys::cbExitInteractive,
    InteractiveScopeChange = vpi_sys::cbInteractiveScopeChange,
    UnresolvedSystf = vpi_sys::cbUnresolvedSystf,
    AtEndOfSimTime = vpi_sys::cbAtEndOfSimTime,
}
