use num_derive::{FromPrimitive, ToPrimitive};

#[repr(u32)]
#[derive(FromPrimitive, ToPrimitive)]
pub enum ObjectType {
    Constant = vpi_sys::vpiConstant,
    Parameter = vpi_sys::vpiParameter,
    Net = vpi_sys::vpiNet,
    NetBit = vpi_sys::vpiNetBit,
    Reg = vpi_sys::vpiReg,
    RegBit = vpi_sys::vpiRegBit,
    TimeVar = vpi_sys::vpiTimeVar,
    RealVar = vpi_sys::vpiRealVar,
    IntegerVar = vpi_sys::vpiIntegerVar,
    LeftRange = vpi_sys::vpiLeftRange,
    RightRange = vpi_sys::vpiRightRange,
    Memory = vpi_sys::vpiMemory,
    MemoryWord = vpi_sys::vpiMemoryWord,
    Function = vpi_sys::vpiFunction,
    InterModPath = vpi_sys::vpiInterModPath,
    Iterator = vpi_sys::vpiIterator,
    ModPath = vpi_sys::vpiModPath,
    Module = vpi_sys::vpiModule,
    NamedBegin = vpi_sys::vpiNamedBegin,
    NamedEvent = vpi_sys::vpiNamedEvent,
    NamedFork = vpi_sys::vpiNamedFork,
    Task = vpi_sys::vpiTask,
    UdpDefn = vpi_sys::vpiUdpDefn,
    UserSystf = vpi_sys::vpiUserSystf,
    SysFuncCall = vpi_sys::vpiSysFuncCall,
    SysTaskCall = vpi_sys::vpiSysTaskCall,
    NetArray = vpi_sys::vpiNetArray,
    Parent = vpi_sys::vpiParent,
    Scope = vpi_sys::vpiScope,
    Argument = vpi_sys::vpiArgument,
    InternalScope = vpi_sys::vpiInternalScope,
    ModPathIn = vpi_sys::vpiModPathIn,
    ModPathOut = vpi_sys::vpiModPathOut,
    Variables = vpi_sys::vpiVariables,
    Expr = vpi_sys::vpiExpr,
    Callback = vpi_sys::vpiCallback,
    RegArray = vpi_sys::vpiRegArray,
    GenScope = vpi_sys::vpiGenScope,
    Always = vpi_sys::vpiAlways,
    // One to one
    Condition = vpi_sys::vpiCondition,
    Delay = vpi_sys::vpiDelay,
    ElseStmt = vpi_sys::vpiElseStmt,
    ForIncStmt = vpi_sys::vpiForIncStmt,
    ForInitStmt = vpi_sys::vpiForInitStmt,
    HighConn = vpi_sys::vpiHighConn,
    Lhs = vpi_sys::vpiLhs,
    Index = vpi_sys::vpiIndex,
    LowConn = vpi_sys::vpiLowConn,
    Rhs = vpi_sys::vpiRhs,
    SysTfCall = vpi_sys::vpiSysTfCall,
    TchkDataTerm = vpi_sys::vpiTchkDataTerm,
    TchkNotifier = vpi_sys::vpiTchkNotifier,
    TchRefTerm = vpi_sys::vpiTchkRefTerm,
    // One to many
    Bit = vpi_sys::vpiBit,
    Driver = vpi_sys::vpiDriver,
    Load = vpi_sys::vpiLoad,
    ModDataPathIn = vpi_sys::vpiModDataPathIn,
    Operand = vpi_sys::vpiOperand,
    PortInst = vpi_sys::vpiPortInst,
    Process = vpi_sys::vpiProcess,
    Use = vpi_sys::vpiUse,
    // One to one or one to many
    Primitive = vpi_sys::vpiPrimitive,
    Stmt = vpi_sys::vpiStmt,
    // 2001
    ActiveTimeFormat = vpi_sys::vpiActiveTimeFormat,
    InTerm = vpi_sys::vpiInTerm,
    InstanceArray = vpi_sys::vpiInstanceArray,
    LocalDriver = vpi_sys::vpiLocalDriver,
    LocalLoad = vpi_sys::vpiLocalLoad,
    OutTerm = vpi_sys::vpiOutTerm,
    Ports = vpi_sys::vpiPorts,
    SimNet = vpi_sys::vpiSimNet,
    TaskFunc = vpi_sys::vpiTaskFunc,
    // 2005
    BaseExpr = vpi_sys::vpiBaseExpr,
    WidthExpr = vpi_sys::vpiWidthExpr,
    // 2009
    Automatics = vpi_sys::vpiAutomatics,
}
