pub enum ObjectType {
    Constant,
    Parameter,
    Net,
    NetBit,
    Reg,
    RegBit,
    TimeVar,
    RealVar,
    IntegerVar,
    LeftRange,
    RightRange,
    Memory,
    MemoryWord,
    Function,
    InterModPath,
    Iterator,
    ModPath,
    Module,
    NamedBegin,
    NamedEvent,
    NamedFork,
    Task,
    UdpDefn,
    UserSystf,
    SysFuncCall,
    SysTaskCall,
    NetArray,
    Parent,
    Scope,
    Argument,
    InternalScope,
    ModPathIn,
    ModPathOut,
    Variables,
    Expr,
    Callback,
    RegArray,
    GenScope,
    Unknown(u32),
}

impl From<u32> for ObjectType {
    fn from(value: u32) -> Self {
        match value {
            vpi_sys::vpiConstant => ObjectType::Constant,
            vpi_sys::vpiParameter => ObjectType::Parameter,
            vpi_sys::vpiNet => ObjectType::Net,
            vpi_sys::vpiReg => ObjectType::Reg,
            vpi_sys::vpiRegBit => ObjectType::RegBit,
            vpi_sys::vpiTimeVar => ObjectType::TimeVar,
            vpi_sys::vpiRealVar => ObjectType::RealVar,
            vpi_sys::vpiIntegerVar => ObjectType::IntegerVar,
            vpi_sys::vpiLeftRange => ObjectType::LeftRange,
            vpi_sys::vpiRightRange => ObjectType::RightRange,
            vpi_sys::vpiMemory => ObjectType::Memory,
            vpi_sys::vpiMemoryWord => ObjectType::MemoryWord,
            vpi_sys::vpiFunction => ObjectType::Function,
            vpi_sys::vpiInterModPath => ObjectType::InterModPath,
            vpi_sys::vpiIterator => ObjectType::Iterator,
            vpi_sys::vpiModPath => ObjectType::ModPath,
            vpi_sys::vpiModule => ObjectType::Module,
            vpi_sys::vpiNamedBegin => ObjectType::NamedBegin,
            vpi_sys::vpiNamedEvent => ObjectType::NamedEvent,
            vpi_sys::vpiNamedFork => ObjectType::NamedFork,
            vpi_sys::vpiTask => ObjectType::Task,
            vpi_sys::vpiUdpDefn => ObjectType::UdpDefn,
            vpi_sys::vpiUserSystf => ObjectType::UserSystf,
            vpi_sys::vpiSysFuncCall => ObjectType::SysFuncCall,
            vpi_sys::vpiSysTaskCall => ObjectType::SysTaskCall,
            vpi_sys::vpiNetArray => ObjectType::NetArray,
            vpi_sys::vpiParent => ObjectType::Parent,
            vpi_sys::vpiScope => ObjectType::Scope,
            vpi_sys::vpiArgument => ObjectType::Argument,
            vpi_sys::vpiInternalScope => ObjectType::InternalScope,
            vpi_sys::vpiModPathIn => ObjectType::ModPathIn,
            vpi_sys::vpiModPathOut => ObjectType::ModPathOut,
            vpi_sys::vpiVariables => ObjectType::Variables,
            vpi_sys::vpiExpr => ObjectType::Expr,
            vpi_sys::vpiCallback => ObjectType::Callback,
            vpi_sys::vpiRegArray => ObjectType::RegArray,
            vpi_sys::vpiGenScope => ObjectType::GenScope,
            other => ObjectType::Unknown(other),
        }
    }
}
